### ISSUE TITLE
Determine best method for specifying reading/writing multiple file formats CLI side

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsd_format#10]
The CLI interface could automatically determine readers and writers based on the input and output file extensions but not if reading/writing stdin/stdout.  GPSDReader/Writer could handle this but if the user is using the API then they are responsible for opening and closing their own files and creating their own readers and writers.  The solution is to at least create a helper function that gets a reader/writer class and probably one or two additional functions that handle abstraction at different levels, or maybe a click type that wraps GPSDReader/Writer

It is important to remember that this is primarily an issue for the CLI and should be solved without needlessly complicating the GPSDReader/Writer.  The following criteria should be considered:

1. Must support streaming from stdin and to stdout.
2. Use the `click.File()` type for infile and outfile to automatically switch to stdin and stdout.
3. Multiple conversion tools need access to this information so it is likely best handled in the `cli/main()` group and `ctx.obj`.

```python
def get_reader(name):
    """
    Get a reader class by name.
    
    Parameters
    ----------------
    name : str
        Name of desired reader.
    
    Raises
    ---------
    ValueError
        Invalid reader name.
    
    Returns
    ----------
    NewlineJSONReader or MsgPackReader or ...
    """
    if name.lower() == 'newlinejson':
        return NewlineJSONReader
    elif name.lower() == 'msgpack':
        return MsgPackReader
    else:
        raise ValueError("Invalid reader: %s" % name)
```

**Comment by redhog** [comment]
https://github.com/SkyTruth/gpsd_format/pull/14

**Comment by redhog** [comment]
Check API examples under https://github.com/SkyTruth/gpsd_format/blob/master/NOTES.rst

**Comment by redhog** [comment]
All non-cli parts of this have been implemented in the new-api branch.

**Comment by geowurster** [comment]
@redhog check this out https://github.com/SkyTruth/gpsd_format/pull/19.

**Comment by redhog** [comment]
I would actually consider this done. Shall we close this?
