### ISSUE TITLE
Sample data and test files

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsd_format#13]
Need some actual mid-sized test files and sample data

Collect example messages from
- [x] GPSD test suite
- [x] libais test suits
- [ ] Real data feeds

**Comment by redhog** [comment]
Added test data from libais and gpsd in https://github.com/SkyTruth/gpsd_format/commit/978099dc9a25e584adeca066ba691488bd609768

**Comment by redhog** [comment]
I think collecting samples from real data feeds should be an ongoing thing rather than a ticket, so I'm going to remove that and close this ticket - we have enough validation data to find lots of schema problems already :P
