### ISSUE TITLE
We need a better name ...

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsd_format#17]

**Comment by geowurster** [comment]
@redhog have you thought of anything better than `gpsdio`?  Now that I type it out I don't really like how it looks.

**Comment by redhog** [comment]
No, haven't :(

I think I like gpsdio better than gpsd_format, but only by a tiny bit...

**Comment by geowurster** [comment]
`typeais`?  I thought of that when we first proposed breaking the I/O functionality into its own repo.

**Comment by geowurster** [comment]
Done - gpsdio

**Comment by redhog** [comment]
Will you rename the repository, and the package?

**Comment by geowurster** [comment]
Yeah in a bit.  I'll give you a heads up though.
