### ISSUE TITLE
Rename schema.row2message() to something

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsd_format#5]
This function takes a dictionary, removes fields that are not a part of the declared type, and adds defaults for fields that are not present.

**Comment by redhog** [comment]
What about any of these

schema.coerce_msg
schema.complete_msg

Maybe we should even split it into two methods, one to add missing attributes and another to remove extraneous ones?

schema.complete_msg & schema.filter_msg

?

**Comment by geowurster** [comment]
I propose 3 different functions:

1. `complete_msg()` - Add any fields that are not present with their default values
2. `strip_msg()` - Remove any fields that do not belong
3. `force_msg()` - Calls the other two functions and maybe has an optional flag that floors/ceilings values that are out of range and converts values that are the wrong type to the default value for that field?  We maybe want to add that functionality later.

**Comment by redhog** [comment]
Ok, that sounds good to me.

**Comment by redhog** [comment]
Done in https://github.com/SkyTruth/gpsd_format/commit/741ea2c6517ef32aff76e329a033f120161e0e40
